// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA34EnF29ZjLJfkmuvoSaLz6gXbL8-KoaA',
    appId: '1:851441089572:web:4444f370afeca97c566cb1',
    messagingSenderId: '851441089572',
    projectId: 'techstore-produtos',
    authDomain: 'techstore-produtos.firebaseapp.com',
    storageBucket: 'techstore-produtos.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA34EnF29ZjLJfkmuvoSaLz6gXbL8-KoaA',
    appId: '1:851441089572:android:9b09d9ceafd25b4c566cb1',
    messagingSenderId: '851441089572',
    projectId: 'techstore-produtos',
    storageBucket: 'techstore-produtos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA34EnF29ZjLJfkmuvoSaLz6gXbL8-KoaA',
    appId: '1:851441089572:ios:0f0ea96db3973051566cb1',
    messagingSenderId: '851441089572',
    projectId: 'techstore-produtos',
    storageBucket: 'techstore-produtos.firebasestorage.app',
    iosBundleId: 'com.example.appExemploComponentes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA34EnF29ZjLJfkmuvoSaLz6gXbL8-KoaA',
    appId: '1:851441089572:ios:0f0ea96db3973051566cb1',
    messagingSenderId: '851441089572',
    projectId: 'techstore-produtos',
    storageBucket: 'techstore-produtos.firebasestorage.app',
    iosBundleId: 'com.example.app_exemplo_componentes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA34EnF29ZjLJfkmuvoSaLz6gXbL8-KoaA',
    appId: '1:851441089572:web:b8af1414cc98e387566cb1',
    messagingSenderId: '851441089572',
    projectId: 'techstore-produtos',
    authDomain: 'techstore-produtos.firebaseapp.com',
    storageBucket: 'techstore-produtos.firebasestorage.app',
  );
}
