// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwIyYU5lmCx5i8qDYugf_AV4cpBgSWf7Q',
    appId: '1:851441089572:web:4444f370afeca97c566cb1',
    messagingSenderId: '851441089572',
    projectId: 'techstore-produtos',
    authDomain: 'techstore-produtos.firebaseapp.com',
    storageBucket: 'techstore-produtos.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA34EnF29ZjLJfkmuvoSaLz6gXbL8-KoaA',
    appId: '1:851441089572:android:2979be88e52b9a44566cb1',
    messagingSenderId: '851441089572',
    projectId: 'techstore-produtos',
    storageBucket: 'techstore-produtos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAygwJ3dLUhRWV4SeS-pz2SYVxdegiSCA8',
    appId: '1:851441089572:ios:b80f1740a42282ea566cb1',
    messagingSenderId: '851441089572',
    projectId: 'techstore-produtos',
    storageBucket: 'techstore-produtos.firebasestorage.app',
    iosBundleId: 'com.example.appComBanco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAygwJ3dLUhRWV4SeS-pz2SYVxdegiSCA8',
    appId: '1:851441089572:ios:b80f1740a42282ea566cb1',
    messagingSenderId: '851441089572',
    projectId: 'techstore-produtos',
    storageBucket: 'techstore-produtos.firebasestorage.app',
    iosBundleId: 'com.example.appComBanco',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwIyYU5lmCx5i8qDYugf_AV4cpBgSWf7Q',
    appId: '1:851441089572:web:caa7549df59da7ff566cb1',
    messagingSenderId: '851441089572',
    projectId: 'techstore-produtos',
    authDomain: 'techstore-produtos.firebaseapp.com',
    storageBucket: 'techstore-produtos.firebasestorage.app',
  );

}