// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARqz8Y2cj_flgIQaM4W85LQL5Yit9-mSM',
    appId: '1:547438840713:web:181969f5405c8ceb622f58',
    messagingSenderId: '547438840713',
    projectId: 'teste-5dc1e',
    authDomain: 'teste-5dc1e.firebaseapp.com',
    storageBucket: 'teste-5dc1e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASirvt_yW6dAUcOwEw0xF_rEqCNCVTcGY',
    appId: '1:547438840713:android:b9f86259d2d1e435622f58',
    messagingSenderId: '547438840713',
    projectId: 'teste-5dc1e',
    storageBucket: 'teste-5dc1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_YzEy0apKtZqOFnCmIUvufc6CsSD4zn4',
    appId: '1:547438840713:ios:6c438c1662fff9ea622f58',
    messagingSenderId: '547438840713',
    projectId: 'teste-5dc1e',
    storageBucket: 'teste-5dc1e.firebasestorage.app',
    iosBundleId: 'com.example.appComBanco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_YzEy0apKtZqOFnCmIUvufc6CsSD4zn4',
    appId: '1:547438840713:ios:6c438c1662fff9ea622f58',
    messagingSenderId: '547438840713',
    projectId: 'teste-5dc1e',
    storageBucket: 'teste-5dc1e.firebasestorage.app',
    iosBundleId: 'com.example.appComBanco',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARqz8Y2cj_flgIQaM4W85LQL5Yit9-mSM',
    appId: '1:547438840713:web:4302af06f256f826622f58',
    messagingSenderId: '547438840713',
    projectId: 'teste-5dc1e',
    authDomain: 'teste-5dc1e.firebaseapp.com',
    storageBucket: 'teste-5dc1e.firebasestorage.app',
  );
}
