// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-uwrTnlYPfVB-bTr-vq2BhUP0Wbw7AXo',
    appId: '1:181506422611:web:09ad55b6af8cae45f453a6',
    messagingSenderId: '181506422611',
    projectId: 'techstoren-14ebc',
    authDomain: 'techstoren-14ebc.firebaseapp.com',
    storageBucket: 'techstoren-14ebc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHUueGsVOmEJlZvpFxxdBOjwmoNY9UrpE',
    appId: '1:181506422611:android:24dace9e41e55b98f453a6',
    messagingSenderId: '181506422611',
    projectId: 'techstoren-14ebc',
    storageBucket: 'techstoren-14ebc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1aVkQZTHqNblnB7hPBDaAHw0H6DTZ918',
    appId: '1:181506422611:ios:9ace98123ee11e2cf453a6',
    messagingSenderId: '181506422611',
    projectId: 'techstoren-14ebc',
    storageBucket: 'techstoren-14ebc.firebasestorage.app',
    iosBundleId: 'com.example.appComBanco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1aVkQZTHqNblnB7hPBDaAHw0H6DTZ918',
    appId: '1:181506422611:ios:9ace98123ee11e2cf453a6',
    messagingSenderId: '181506422611',
    projectId: 'techstoren-14ebc',
    storageBucket: 'techstoren-14ebc.firebasestorage.app',
    iosBundleId: 'com.example.appComBanco',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-uwrTnlYPfVB-bTr-vq2BhUP0Wbw7AXo',
    appId: '1:181506422611:web:33a53e8d93bc1d5ff453a6',
    messagingSenderId: '181506422611',
    projectId: 'techstoren-14ebc',
    authDomain: 'techstoren-14ebc.firebaseapp.com',
    storageBucket: 'techstoren-14ebc.firebasestorage.app',
  );

}